### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by 1isabelle1** [c0zaut/RKLLM-Gradio#4]
**Describe the bug**
An error happened when running  rkllm_server_gradio.py for chatglm3-6b-rk3588-1.1.2
I've downloaded the model locally, but it still seems to be networking for the download?

**Expected behavior**
Should be able to generate the benchmark result

**Screenshots**
Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f45a59ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /self.st_model_id/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45a59ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /self.st_model_id/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45a59ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: d0c73fdd-dc0e-4e09-924c-2f50943bc022)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/blocks.py", line 1574, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/utils.py", line 710, in async_iteration
    return await anext(iterator)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/utils.py", line 704, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/utils.py", line 687, in run_sync_iterator_async
    return next(iterator)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/gradio/utils.py", line 848, in gen_wrapper
    response = next(iterator)
  File "/media/userdata/rkllm-gradio/rkllm_server_gradio.py", line 48, in get_RKLLM_output
    yield from rkllm_model.get_RKLLM_output(history)
  File "/media/userdata/rkllm-gradio/model_class.py", line 171, in get_RKLLM_output
    tokenizer = AutoTokenizer.from_pretrained('self.st_model_id', trust_remote_code=True)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 877, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1017, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/configuration_utils.py", line 633, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/.venv/rkllm-gradio/lib/python3.10/site-packages/transformers/utils/hub.py", line 446, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like self.st_model_id is not the path to a directory containing a file named config.json.

**Comment by 1isabelle1** [comment]
Thanks for your reply. I was sure to download the models under the /models path.

I finally solved the problem by modifying tokenizer = AutoTokenizer.from_pretrained(self.st_model_id, trust_remote_code=True) in the model_class.py file. I replaced self.st_model_id with the real path where the model is located.

**Comment by c0zaut** [comment]
Just about to suggest that - it access HF for the tokenizer. I noticed that trying to just use normal strings did not handle multi-line input properly. I had to manipulate strings and convert newlines to escaped newlines. Unfortunately, sometimes the models took their clues from that and just used literal \n

Glad you figured it out on your own!
