### ISSUE TITLE
Cannot interact with chatbot in webui

### ISSUE THREAD

**Issue by simper** [c0zaut/RKLLM-Gradio#6]
I followed the readme guide, and load the models downloaded from the links in readme, but cannot interact with chatbot in webui, on terminal I got below error message:
```
(rkllm-gradio) pve5:rkllm-gradio:# python rkllm_server_gradio.py                                                                                  <main ✗>
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/components/chatbot.py:225: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  warnings.warn(
/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/chat_interface.py:221: UserWarning: The type of the chatbot does not match the type of the chat interface. The type of the chat interface will be used.Recieved type of chatbot: {chatbot.type}, type of chat interface: {self.type}
  warnings.warn(

No model loaded yet!

* Running on local URL:  http://0.0.0.0:9090

To create a public link, set `share=True` in `launch()`.
No model loaded! Continuing with initialization...
=========INITIALIZING===========
I rkllm: rkllm-runtime version: 1.1.3, rknpu driver version: 0.9.7, platform: RK3588

RKLLM Model, Qwen2.5-7B-Instruct has been initialized successfully！
==============================
Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/routes.py", line 1011, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/blocks.py", line 2011, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/blocks.py", line 1706, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/components/chatbot.py", line 414, in preprocess
    raise Error("Data incompatible with the messages format")
gradio.exceptions.Error: 'Data incompatible with the messages format'
Traceback (most recent call last):
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/blocks.py", line 2011, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/blocks.py", line 1706, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/components/chatbot.py", line 414, in preprocess
    raise Error("Data incompatible with the messages format")
gradio.exceptions.Error: 'Data incompatible with the messages format'
```

The model config block I updated:
```
    "Qwen-2.5-Instruct": {
        "base_config": {
            "st_model_id": "c01zaut/Qwen2.5-7B-Instruct-rk3588-1.1.1",
            "max_context_len": 10000,
            "max_new_tokens": 8192,
            "top_k": 5,
            "top_p": 0.8,
            "temperature": 0.2,
            "repeat_penalty": 1.00,
            "frequency_penalty": 0.2,
            "system_prompt": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."
        },
        "models": {
            "Qwen2.5-1.5B-Instruct": {"filename": "Qwen2.5-1.5B-Instruct-rk3588-w8a8-opt-1-hybrid-ratio-1.0.rkllm"},
            "Qwen2.5-3B-Instruct": {"filename": "Qwen2.5-3B-Instruct-rk3588-w8a8-opt-1-hybrid-ratio-1.0.rkllm"},
            "Qwen2.5-7B-Instruct": {"filename": "Qwen2.5-7B-Instruct-rk3588-w8a8_g128-opt-1-hybrid-ratio-1.0.rkllm"},
            "Qwen2.5-Coder-7B-Instruct": {"filename": "Qwen2.5-Coder-7B-Instruct-rk3588-w8a8-opt-0-hybrid-ratio-0.0.rkllm"},
            "Qwen2.5-Coder-1.5B-Instruct-w8a8-hybrid": {"filename": "Qwen2.5-Coder-1.5B-Instruct-rk3588-w8a8-opt-0-hybrid-ratio-1.0.rkllm"}
        },
    },
```

**Comment by c0zaut** [comment]
It seems like there is an issue with the tokenizer. I have just pushed an update the lower the context window back down to 4096. I would recommend using the original `"st_model_id"` value. I just tested it with Qwen 2.5 3B Instruct. I am also using Python 3.12 in Armbian Ubuntu 24.04 BSP. 

![image](https://github.com/user-attachments/assets/aebc3a65-44c1-4aef-9d80-cbb0daabd8a9)
![image](https://github.com/user-attachments/assets/41069522-1437-44f1-b614-da0c356d21de)

```
=========INITIALIZING===========
I rkllm: rkllm-runtime version: 1.1.4, rknpu driver version: 0.9.7, platform: RK3588

RKLLM Model, Qwen2.5-3B-Instruct has been initialized successfully！
==============================
In the heart of an ancient forest, there stood a solitary oak tree, its gnarled branches reaching out like arms to the sky. The oak was known as the Whispering Tree by the local children, for it seemed to speak to them in the soft rustling of leaves and the gentle creaking of its trunk.

One crisp autumn morning, a young girl named Elara wandered into the forest, her heart heavy with sorrow after losing her beloved pet dog. As she sat beneath the oak, her tears mingled with the dew on the leaves, and she felt a familiar presence beside her. It was the tree, its voice now clearer than ever.

"Child," the tree said softly, "I know of your sorrow. You have a friend in me."

Elara looked up, her eyes wide with disbelief. "You can talk?"

The oak nodded. "Yes, my dear. I have been here for many years, and I have seen many lives come and go. I can share my wisdom and comfort those who seek it."

Over the next few days, Elara visited the oak tree every morning. She would sit beneath its branches, sharing her dreams and fears, and the tree would listen intently. As she did so, she noticed that the leaves around her began to change color, and the air around her felt lighter.

One evening, as the sun dipped below the horizon, painting the sky in hues of orange and pink, Elara felt a profound sense of peace. The tree placed a gentle hand on her shoulder. "You have found a new friend," it said. "And you have learned something important about yourself."

Elara looked up at the tree, her heart full of gratitude. "What did I learn?"

The oak smiled. "You learned that you are not alone, and that even in the darkest of times, there is always hope."

From that day forward, Elara visited the oak tree every morning, and the tree continued to be a source of comfort and wisdom for her. The oak tree became a symbol of hope and resilience, standing tall and strong in the heart of the forest, ready to listen to anyone who needed a friend.


--------------------------------------------------------------------------------------
 Stage         Total Time (ms)  Tokens    Time per Token (ms)      Tokens per Second       
--------------------------------------------------------------------------------------
 Prefill       378.03           40        9.45                     105.81                  
 Generate      64474.05         441       147.25                   6.79                    
--------------------------------------------------------------------------------------
```

If it's still failing for you, can you send me the output of `pip freeze` so I can take a look at the versions in your virtual environment?

**Comment by simper** [comment]
With your latest update, it seems work, but token generation using qwen2.5-coder 7B is very slow, around 1.76token/s, not sure whether that is normal?
My terminal output:
```
(rkllm-gradio) pve5:rkllm-gradio:# python rkllm_server_gradio.py                                                                                  <main ✗>
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/root/.venv/rkllm-gradio/lib/python3.11/site-packages/gradio/components/chatbot.py:225: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  warnings.warn(

No model loaded yet!

* Running on local URL:  http://0.0.0.0:9090

To create a public link, set `share=True` in `launch()`.
No model loaded! Continuing with initialization...
=========INITIALIZING===========
I rkllm: rkllm-runtime version: 1.1.4, rknpu driver version: 0.9.7, platform: RK3588

RKLLM Model, Qwen2.5-Coder-7B-Instruct has been initialized successfully！
==============================
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7.30k/7.30k [00:00<00:00, 10.2MB/s]
vocab.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78M/2.78M [00:02<00:00, 966kB/s]
merges.txt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1.67M/1.67M [00:01<00:00, 848kB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7.03M/7.03M [00:03<00:00, 1.98MB/s]
Hello there! How can I assist you today?


--------------------------------------------------------------------------------------
 Stage         Total Time (ms)  Tokens    Time per Token (ms)      Tokens per Second       
--------------------------------------------------------------------------------------
 Prefill       1742.27          30        58.08                    17.22                   
 Generate      5623.78          10        567.45                   1.76                    
--------------------------------------------------------------------------------------
```

**Comment by c0zaut** [comment]
Are you using a microSD card, by any chance? I usually get around 2-3 tok/s using NVMe. Also, if you are using RK3588s board vs full RK3588, your speeds will still be limited. This is due to the s-series using only gen 2 PCIe.

**Comment by simper** [comment]
> Are you using a microSD card, by any chance? I usually get around 2-3 tok/s using NVMe. Also, if you are using RK3588s board vs full RK3588, your speeds will still be limited. This is due to the s-series using only gen 2 PCIe.

No, it is a high speed nvme, and an orangepi 5 plus 32G running armbian 6.1.75 vendor kernel, I got 7+ t/s for the llama 3.2 3B model though…

**Comment by c0zaut** [comment]
I was able to get close to the generation speeds you are reporting with 7B, but the model generated 1K tokens. Even then, it was 1.86 tok/s. I ran the browser session on the Orange Pi 5 Plus, and had some other browser tabs plus two full projects in Visual Code open.
